config_args:
    seed: 14
    maxchars: 16
    subsample: 100
    tokenizer_path: '/cluster/home/jrando/passbert/models/tokenizers/byte_bpe_tokenizer_99/'
    train_data_path: '/cluster/home/jrando/passbert/data/rockyouascii/after/train_16_unique.txt'

model_args:
    n_head: 12
    n_layer: 8
    
training_args:
    per_device_train_batch_size: 2048
    gradient_accumulation_steps: 1
    logging_steps: 250
    save_total_limit: 1
    num_train_epochs: 1
    overwrite_output_dir: true
    fp16: false
    output_dir: '/cluster/home/jrando/passbert/models/passgpt_16chars/'
    report_to: "wandb"
    save_steps: 50000
